### ISSUE TITLE
Dear author, you know that you have done a famous and complex work. Then, I meet a question that proteome data NOT 404

### ISSUE THREAD

**Issue by swj105** [SysBioChalmers/DLKcat#10]
https://github.com/SysBioChalmers/DLKcat/tree/master/BayesianApporach/Data/Proteome_ref.xlsx.  this website did not Find Page 404. Hope you can help me, thank you very much.

**Comment by feiranl** [comment]
Please find it here: https://github.com/SysBioChalmers/DLKcat/blob/master/BayesianApproach/Data/Proteome_ref.xlsx
