### ISSUE TITLE
Dataset problem

### ISSUE THREAD

**Issue by HanselYu** [SysBioChalmers/DLKcat#14]
Thanks for your great work!
I have a question about dataset, the dataset of github has 17010 samples,  including 9529 wildtype and 7481 mutant. But the dataset used in published article only has 16838 samples, is there any difference?
If possible, could you mail me the 16838 samples and other samples in separate format, *han.yu@siat.ac.cn* thanks again!

**Comment by le-yuan** [comment]
Thanks for your interest. The dataset that we described in the published paper contains 16,838 unique entries. The main reason is that we excluded those data entries: (1) substrate SMILES contains "." (2) Kcat value <=0; Please check our code: https://github.com/SysBioChalmers/DLKcat/blob/7064af9b4401de65753543dfa2da7466434ce4d2/DeeplearningApproach/Code/model/preprocess_all.py#L123

**Comment by HanselYu** [comment]
That's true. Thank you very much !

**Comment by jiejiangtao** [comment]
我也有个问题，通过代码我可以看出作者是通过sequence和smile 进行训练的，但是数据里面有部分数据具有相同的sequence和smile值
