### ISSUE TITLE
Example input.tsv file in DeeplearningApproach yields no kcats when run

### ISSUE THREAD

**Issue by HettieC** [SysBioChalmers/DLKcat#15]
Hi, I am hoping to use your DLKcat to predict turnover numbers for a few hundred reactions in a model. In order to do this, I have just tried to run ```python prediction_for_input.py input.tsv``` as detailed in the README.rst file in [DLKcat](https://github.com/SysBioChalmers/DLKcat)/DeeplearningApproach/, but all three of the inputs give a kcat value of "none". Note that this is using the input.tsv file given in the cloned github repository, I have not made any changes. 

Do I need to run the preprocessing folder before I can use the tool to predict kcats? If so, running 
```python brenda_retrieve.py``` gives the following error:
```
Traceback (most recent call last):
  File "../DLKcat/DeeplearningApproach/Code/preprocess/brenda_retrieve.py", line 121, in <module>
    os.chdir(output_path)
FileNotFoundError: [Errno 2] No such file or directory: '../../Data/database/brenda_ec'
```
Does the file ```brenda_ec``` need to be downloaded first? If so, where from? Running ```python brenda_download.py``` returns:

```
File "../DLKcat/DeeplearningApproach/Code/preprocess/brenda_download.py", line 51
    print 'Succesfully constructed ' + previous + ' file.'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Succesfully constructed ' + previous + ' file.')?
```

Please let me know if there is some step that I am missing.

**Comment by feiranl** [comment]
so, just change all tensors to be the same device, you can fix it.
```
fingerprints = torch.LongTensor(fingerprints).to(device)
adjacency = torch.FloatTensor(adjacency).to(device)
words = torch.LongTensor(words).to(device)
```

**Comment by HettieC** [comment]
Thanks for getting back, where do I do this? And should I be replacing ```fingerprints``` , ```device``` etc to something specific to my computer and account?

**Comment by feiranl** [comment]
In the function` prediction_for_input.py` line 254-257

**Comment by HettieC** [comment]
Cheers, that works now
