### ISSUE TITLE
Hyperparameter file for DLKcat

### ISSUE THREAD

**Issue by wangjingjing52** [SysBioChalmers/DLKcat#18]
Hello Yuan,

I am Jingjing Wang, a PhD from the Central South University and research on enzyme activity prediction. I have the honor to learn your work DLkcat, which is a very valuable work for reference. I am trying to run the “run_model.py” under the DeeplearningApproach module. However, the value of the hyperparameter is missing such as "ValueError: not enough values to unpack (expected 14, got 0)" in line 184. Could you please share the Hyperparameter file or help me find it in somewhere? Thank you very much!

**Comment by le-yuan** [comment]
Hello Jingjing,

Thanks for your interest about our work. If you want to run the python script "run_model.py",

I would suggest you to write a small bash script like that:

```
DATASET=all
radius=2
ngram=3
...... 

python run_model.py $DATASET $radius $ngram $other hyperparameters

```
Then you can run the small bash script with various hyperparameters to try the model training process.

**Comment by wangjingjing52** [comment]
Hello Yuan,


Thank you very much！And apologies for my late reply！


Yours Sincerely，
Jingjing Wang




***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SysBioChalmers/DLKcat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 凌晨5:18
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [SysBioChalmers/DLKcat] Hyperparameter file for DLKcat (Issue #18)





 
Hello Jingjing,
 
Thanks for your interest about our work. If you want to run the python script "run_model.py",
 
I would suggest you to write a small bash script like that:
 DATASET=all radius=2 ngram=3 ......  python run_model.py $DATASET $radius $ngram $other hyperparameters  
Then you can run the small bash script with various hyperparameters to try the model training process.

**Comment by wangjingjing52** [comment]
Dear Yuan，



 
Thank you very much for your patience in answering my questions last time. May I proceed to ask you a further question? We would greatly appreciate your patience and understanding!



 
According to our understanding of the paper (Deep learning-based Kcat prediction enables improved enzyme-constrained model reconstruction), DLKcat uses 80% of the dataset as the training set. After the model is trained, the dataset is divided into two test sets, such as wild-type and mutant, to test the model respectively. We would like to know how you consider the data duplication between the test sets and the training set. Thank you!
 
&nbsp;
 
Best Wishes
 
&nbsp;
 
Jingjing Wang





***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SysBioChalmers/DLKcat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 凌晨5:18
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [SysBioChalmers/DLKcat] Hyperparameter file for DLKcat (Issue #18)





 
Hello Jingjing,
 
Thanks for your interest about our work. If you want to run the python script "run_model.py",
 
I would suggest you to write a small bash script like that:
 DATASET=all radius=2 ngram=3 ......  python run_model.py $DATASET $radius $ngram $other hyperparameters  
Then you can run the small bash script with various hyperparameters to try the model training process.
