### ISSUE TITLE
A problem during conducting example

### ISSUE THREAD

**Issue by Shinezhuxin** [SysBioChalmers/DLKcat#2]
(base) PS C:\Users\Lenovo> cd D:\DLKcat-master\DLKcat-master\DeeplearningApproach\Code\example
(base) PS D:\DLKcat-master\DLKcat-master\DeeplearningApproach\Code\example> python prediction_for_input.py input.tsv
Traceback (most recent call last):
  File "prediction_for_input.py", line 14, in <module>
    from rdkit import Chem
  File "D:\Anaconda\lib\site-packages\rdkit\__init__.py", line 38, in <module>
    from . import rdBase
ImportError: DLL load failed while importing rdBase: 找不到指定的模块。

Thank you provides helpful suggestions. When I conducted the software according to the README, it remind me these errors. I have install all package, I don't know the reason appearing this errors. Thank you.

**Comment by le-yuan** [comment]
Thanks for you feedback. I suppose it is a rdkit installation issue. Maybe you can check the answer here: https://stackoverflow.com/questions/70202430/rdkit-importerror-dll-load-failed
