### ISSUE TITLE
isssue about runing prediction_for_input.py

### ISSUE THREAD

**Issue by Songlu0** [SysBioChalmers/DLKcat#20]
Dear researcher，
  I am Dr. Song Lu from East China University of Science and Technology. I tryied to use DLKcat to predict Kcat, but I have met a issue. I hope you can help me. When I run "prediction_for_input.py' ，an error occurs.
Traceback (most recent call last):
  File "G:\Anaconda-ProgramData\anaconda3\envs\Aconda\DLKcat-1.0.0\DLKcat-1.0.0\DeeplearningApproach\Code\example\prediction_for_input.py", line 276, in <module>
    main()
  File "G:\Anaconda-ProgramData\anaconda3\envs\Aconda\DLKcat-1.0.0\DLKcat-1.0.0\DeeplearningApproach\Code\example\prediction_for_input.py", line 166, in main
    name = sys.argv[1:][0]
IndexError: list index out of range
Process finished with exit code 1

The code in "prediction_for_input.py" is
def main() :
    name = sys.argv[1:][0]
    print(name)
    # with open('./input.tsv', 'r') as infile :
    with open(name, 'r') as infile :
        lines = infile.readlines()

How can I solove it？

Sincerely yours

**Comment by Songlu0** [comment]
我用终端运行可以解决上述问题，但是输出的结果却显示None，请问这又该如何解决，是要先运行model.py，然后再是预测么？
我运行model.py时，对herparament参数进行了设置，在pycharm终端输入命令
(anaconda3) G:\Anaconda-ProgramData\anaconda3\envs\Aconda\DLKcat-1.0.0\DLKcat-1.0.0\DeeplearningApproach\Code\example>python model.py --DATASET  --radius  --ngram   --setting --dim  --layer_gnn  --window  --layer_cnn  --lr  --lr_decay  --decay_interval  --weight_decay  --iteration

但结果是
Traceback (most recent call last):
  File "G:\Anaconda-ProgramData\anaconda3\envs\Aconda\DLKcat-1.0.0\DLKcat-1.0.0\DeeplearningApproach\Code\example\model.py", line 181, in <module>
    (DATASET, radius, ngram, dim, layer_gnn, window, layer_cnn, layer_output, lr, lr_decay, decay_interval, weight_decay, iteration,
ValueError: not enough values to unpack (expected 14, got 13)
我得到的值少了，请问这个又该怎么解决呢

**Comment by KimHe** [comment]
You can run like this:
`python run_model.py all 2 3 20 3 11 3 0.001 0.5 10 0.000001 50 1234` to get the trained model for further prediction.
BUT, the resulting model from the _above_ running differs from the model stored under the result directory.
The feature tensors saved under INPUT directory probably are manually crafted.

**Comment by Songlu0** [comment]
Thanks for your suggestion, I will try again to train a better model.&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Qiaole He ***@***.***&gt;
Date: Thu,Jul 20,2023 2:52 PM
To: SysBioChalmers/DLKcat ***@***.***&gt;
Cc: Song lu ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [SysBioChalmers/DLKcat] isssue about runingprediction_for_input.py (Issue #20)





 
You can run like this:
 python run_model.py all 2 3 20 3 11 3 0.001 0.5 10 0.000001 50 1234 to get the trained model for further prediction.
 BUT, the resulting model from the above running differs from the model stored under the result directory.
 The feature tensors saved under INPUT directory probably are manually crafted.

**Comment by feiranl** [comment]
Please follow the instruction to run the prediction. If you still met the issue, feel free to open the issue again.
