### ISSUE TITLE
Unable to reproduce the results in Fig. 2a.

### ISSUE THREAD

**Issue by zchwang** [SysBioChalmers/DLKcat#26]
Hi,

DLKcat is an interesting work. But it is difficult for me to find suitable parameters to reproduce the results in Fig. 2a, and there is even a significant discrepancy. Can you provide the parameters corresponding to the data in fig.2a? Looking forward to your reply.

Best regards!

**Comment by feiranl** [comment]
Hi, Thanks for your interest. We provided all code and data for generating each figure. If you mean you want to retrain the model, please follow our guidelines for training. The related training parameters are encoded in the name of output(https://github.com/SysBioChalmers/DLKcat/blob/master/DeeplearningApproach/Results/output/MAEs--all--radius2--ngram3--dim20--layer_gnn3--window11--layer_cnn3--layer_output3--lr1e-3--lr_decay0.5--decay_interval10--weight_decay1e-6--iteration50.txt). If your RMSE is not reducing, please check the environment and previous issues for how to solve this.  If you still have issues, feel free to ask.

**Comment by zchwang** [comment]
Thanks a lot for your response. it's very helpful.

Best regards.
