### ISSUE TITLE
find the sequence

### ISSUE THREAD

**Issue by 17dacheng** [SysBioChalmers/DLKcat#27]
Dear researcher, 

i use brenda_kcat_clean.py to get kcat data file, use ec number and organism in brenda_sequence_organism.py file to get sequences. 

for each row of kcat data file (each reaction), there are ec number, organism and substrate (no uniprot id). if i use ec number and organism query, it might find many sequences with corresponding uniprot id. the question is how to know which sequence in found sequences is for this reaction?  thanks.

**Comment by lhallee** [comment]
I second this! @feiranl @le-yuan how do you guys get sequence data from BRENDA?

**Comment by le-yuan** [comment]
When querying the BRENDA API using EC number and organism as the input, we only retained those entries where a single sequence was identified with its corresponding UniProt ID.

**Comment by 17dacheng** [comment]
thanks for answering. but it seems there is no uniprot id for brenda and in brenda_sequence_organism.py file. if there is, we can directly find sequence from uniprot
