### ISSUE TITLE
Loss calculation confusion

### ISSUE THREAD

**Issue by Frostday** [SysBioChalmers/DLKcat#8]
Hi,
In [run_model.py](https://github.com/SysBioChalmers/DLKcat/blob/master/DeeplearningApproach/Code/model/run_model.py), I noticed that you had calculated the loss on log10 scaled values. Like, the data was initially scaled using the log2 function, then you unscaled the predictions using math.pow(2, value) and finally scaled them again using the log10 function before calculating the losses. Is there any reason for that?

I tried calculating the loss on unscaled data (removing the log10 transformation) and the values were very bad, to the point where they didn't make any sense. So, I was hoping that you could clear this confusion.

**Comment by Frostday** [comment]
Also, is there a specific reason for using log2 to scale all the Kcat values instead of other scalars like MinMaxScaler?

**Comment by feiranl** [comment]
Hi, this is due to that we found log2 and found it works better than log10. Then to convert that into log10 is to facilitate the comparison with other deep learning model.
