### ISSUE TITLE
nomoudule name SOAPpy

### ISSUE THREAD

**Issue by swj105** [SysBioChalmers/DLKcat#9]
excuse me, I run the brenda_retrieve.py ,always erro not SOAPpy. I had tried many version about installing SOAPpy. I have no idea about this, could you help me slove this problem. Your model which reconstruction be uesd bayesianapproach and DL was very meaningful for the Biological experiments. Thank you for your work.

**Comment by feiranl** [comment]
Hi, sorry for the late reply. Could you print out the packages you have installed by running conda list or pip list?
